Feature/menu
andriitomilov/dream-team-14 pull request #6
Opened 2022-12-10 18:58 UTC by VeronikaKodlubovska

add start files of menu mob

2022-12-10 19:13 UTC, andriitomilov commented on src/partials/restaurant-page/menu.html
> +    </div>
Обгорнути весь контент секції у div з классом container

2022-12-10 19:18 UTC, andriitomilov commented on src/partials/restaurant-page/menu.html
> +<section>
в тег section додати класс menu-section та задати паддінги:
padding-top: 32px;
padding-bottom: 32px
з планшетної версії
padding-top: 40px;
padding-bottom: 40px
десктопна версія
padding-top: 60px;
padding-bottom: 60px

2022-12-10 19:21 UTC, andriitomilov commented on src/partials/restaurant-page/menu.html
> +    <h1>МЕНЮ РЕСТОРАНУ</h1>
Згідно ТЗ в нас h1 знаходиться у секції Hero
 h1 має бути один на сторінці, тому замінити всі заголовки
 h1 на h2 
 h2 на h3 і так далі

2022-12-10 19:40 UTC, andriitomilov commented on src/partials/restaurant-page/menu.html
> +    </div>
У вас є обгортка menu-flex, я так розумію, щоб потім на планшетній версії можна було флексами вистроїти все
Перші дві таблиці ви обгорнули у div
Потрібно і наступні три також обгорнути у div

2022-12-10 19:54 UTC, andriitomilov commented on src/partials/restaurant-page/menu.html
> +        <h1>МЕНЮ РЕСТОРАНУ</h1>
По ТЗ у нас h1 заголовок у героя
На одній сторінці має бути один h1
Тому замінити h1 на h2, h2 на h3 і т.д.

2022-12-10 19:56 UTC, andriitomilov commented on src/partials/restaurant-page/menu.html
> +    </div>
Ви створили обгортку menu-flex для офрмлення починаючи з планшетної версії
Але обгорнули у div тільки перші дві таблиці
Інши 3 потрібно також обгорнути у div

2022-12-10 19:58 UTC, andriitomilov commented on src/sass/layout/restaurant-page/_menu.scss
> +h1 {
Погана практика задавати стилі на теги
Придумайте класи 
наприклад для заголовка сторінки menu-section__title
для підзаголовка menu-section__subtitle і так далі

2022-12-10 19:58 UTC, andriitomilov requested changes
Ви забули обгорнути увесь контент секції в div із класом  container

2022-12-11 16:22 UTC, VeronikaKodlubovska commented on src/partials/restaurant-page/menu.html
> +    </div>
Виправлено

2022-12-11 16:22 UTC, VeronikaKodlubovska commented on src/partials/restaurant-page/menu.html
> +<section>
Виправлено

2022-12-11 16:22 UTC, VeronikaKodlubovska commented on src/partials/restaurant-page/menu.html
> +    <h1>МЕНЮ РЕСТОРАНУ</h1>
Виправлено

2022-12-11 16:22 UTC, VeronikaKodlubovska commented on src/partials/restaurant-page/menu.html
> +    </div>
Виправлено

2022-12-11 16:22 UTC, VeronikaKodlubovska commented on src/partials/restaurant-page/menu.html
> +        <h1>МЕНЮ РЕСТОРАНУ</h1>
Виправлено

2022-12-11 16:22 UTC, VeronikaKodlubovska commented on src/partials/restaurant-page/menu.html
> +    </div>
Виправлено

2022-12-11 16:23 UTC, VeronikaKodlubovska commented on src/sass/layout/restaurant-page/_menu.scss
> +h1 {
Виправлено

2022-12-11 16:34 UTC, VeronikaKodlubovska reviewed
Всі зміни внесла.

2022-12-11 18:06 UTC, andriitomilov approved these changes
+

2022-12-11 18:06 UTC, merged